# Generated by Django 6.0.3 on 2026-03-26 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('posicion_fila', models.IntegerField()),
                ('posicion_columna', models.IntegerField()),
                ('filas_tubos', models.IntegerField(default=9)),
                ('columnas_tubos', models.IntegerField(default=9)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudio', models.CharField(help_text='Ej: DAVOS', max_length=100)),
                ('investigador_principal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Ultracongelador 1', max_length=50, verbose_name='Nombre del Equipo')),
                ('modelo', models.CharField(blank=True, help_text='Ej: Thermo Scientific Revco', max_length=50, verbose_name='Modelo/Marca')),
                ('temperatura', models.CharField(default='-80°C', max_length=20, verbose_name='Temperatura de Operación')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Sala 2, Pasillo A', max_length=100, verbose_name='Ubicación Física')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(help_text='Ej: LOTE-DAVOS-001', max_length=100, unique=True, verbose_name='Código de Lote (Manual)')),
                ('registro_interno', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Registro Interno (Sistema)')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='MuestraBiologica',
            fields=[
                ('bsi_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('sample_id', models.CharField(max_length=50)),
                ('sequence', models.IntegerField(default=1)),
                ('material_type', models.CharField(help_text='Ej: Filtro pasivo, Suero', max_length=50)),
                ('vial_type', models.CharField(max_length=50)),
                ('vial_status', models.CharField(default='Disponible', max_length=50)),
                ('date_drawn', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.estudio')),
                ('entry_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.registroingreso', verbose_name='Lote de Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='PosicionTubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(help_text='Fila (Ej: A, B, C)', max_length=5)),
                ('col', models.IntegerField(help_text='Columna (Ej: 1, 2, 3)')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='inventario.caja')),
                ('muestra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.muestrabiologica')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Rack A1', max_length=50)),
                ('filas_alto', models.IntegerField(help_text='Cantidad de cajas hacia arriba (ej: 5)')),
                ('columnas_ancho', models.IntegerField(help_text='Cantidad de cajas hacia el lado (ej: 5)')),
                ('freezer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventario.freezer', verbose_name='Freezer Asignado')),
            ],
        ),
        migrations.AddField(
            model_name='caja',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='inventario.rack'),
        ),
    ]
