# Generated by Django 6.0.3 on 2026-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='columnas_tubos',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='filas_tubos',
        ),
        migrations.AddField(
            model_name='caja',
            name='codigo_caja',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='caja',
            name='columnas',
            field=models.IntegerField(default=9, help_text='Ej: 9, 10, etc.'),
        ),
        migrations.AddField(
            model_name='caja',
            name='filas',
            field=models.IntegerField(default=9, help_text='Ej: 9 para cajas estándar, 10 para cajas de 100'),
        ),
    ]
