# Generated by Django 6.0.3 on 2026-03-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_caja_columnas_tubos_remove_caja_filas_tubos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posiciontubo',
            name='muestra',
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='ubicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestra', to='inventario.posiciontubo', verbose_name='Ubicación en Caja (Hueco)'),
        ),
    ]
