# Generated by Django 6.0.3 on 2026-03-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_posiciontubo_muestra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='columnas',
            new_name='columnas_de_caja',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='filas',
            new_name='filas_de_caja',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='posicion_columna',
            new_name='posicion_columna_en_rack',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='posicion_fila',
            new_name='posicion_fila_en_rack',
        ),
    ]
