# Generated by Django 6.0.3 on 2026-03-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_columnas_caja_columnas_de_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestrabiologica',
            name='date_frozen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Congelación'),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='hemolyzed',
            field=models.BooleanField(default=False, verbose_name='Hemolizada'),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='parent_id',
            field=models.CharField(blank=True, help_text='BSI ID de la muestra original (si es alícuota)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='project',
            field=models.CharField(blank=True, help_text='Proyecto específico (Ej: Sub-proyecto de DAVOS)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='subject_id',
            field=models.CharField(blank=True, help_text='ID anonimizado del paciente/participante', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='thaws',
            field=models.IntegerField(default=0, help_text='Número de ciclos de descongelamiento'),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='vial_warnings',
            field=models.TextField(blank=True, help_text='Advertencias o notas sobre la calidad del vial', null=True),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Volumen de la muestra (ej: 500.000)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='muestrabiologica',
            name='volume_unit',
            field=models.CharField(blank=True, help_text='Unidad de medida (ej: µL, mL)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='muestrabiologica',
            name='date_drawn',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Extracción'),
        ),
        migrations.AlterField(
            model_name='muestrabiologica',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AlterField(
            model_name='muestrabiologica',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.estudio'),
        ),
    ]
