# Generated by Django 6.0.3 on 2026-03-31 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_muestrabiologica_date_frozen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('SALIDA', 'Salida de Freezer (Consumo/Envío)'), ('RETORNO', 'Retorno a Freezer'), ('REUBICACION', 'Reubicación Interna'), ('AUDITORIA', 'Revisión de Auditoría (Inventario)')], max_length=20)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(help_text='Ej: Extracción de ADN, Envío a laboratorio externo, etc.')),
                ('destino', models.CharField(blank=True, help_text='Lugar o persona que recibe la muestra', max_length=100, null=True)),
                ('ubicacion_previa', models.CharField(blank=True, help_text='Queda guardado como texto por si la caja original se borra', max_length=100, null=True)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='inventario.muestrabiologica')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el movimiento', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
