# Generated by Django 6.0.3 on 2026-04-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_movimientomuestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestrabiologica',
            name='entry_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.registroingreso', verbose_name='Lote de Ingreso'),
        ),
    ]
