# Generated by Django 6.0.3 on 2026-04-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_tipomaterial_tipovial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='tubos_por_caja_estandar',
            field=models.IntegerField(default=100, help_text='100 para criocajas 10x10, 81 para criocajas 9x9'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='columnas_ancho',
            field=models.IntegerField(help_text='Cantidad de cajas hacia el lado (ej: 5, 4)'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='filas_alto',
            field=models.IntegerField(help_text='Cantidad de cajas hacia arriba (ej: 5, 7)'),
        ),
    ]
